// source: senml.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.senml_protobuf.Record');
goog.provide('proto.senml_protobuf.Record.BasesumoptionalCase');
goog.provide('proto.senml_protobuf.Record.BasevalueoptionalCase');
goog.provide('proto.senml_protobuf.Record.SumoptionalCase');
goog.provide('proto.senml_protobuf.Record.ValueoneofCase');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.senml_protobuf.Record = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.senml_protobuf.Record.oneofGroups_);
};
goog.inherits(proto.senml_protobuf.Record, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.senml_protobuf.Record.displayName = 'proto.senml_protobuf.Record';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.senml_protobuf.Record.oneofGroups_ = [[5],[6],[11,12,13,14],[15]];

/**
 * @enum {number}
 */
proto.senml_protobuf.Record.BasevalueoptionalCase = {
  BASEVALUEOPTIONAL_NOT_SET: 0,
  BASEVALUE: 5
};

/**
 * @return {proto.senml_protobuf.Record.BasevalueoptionalCase}
 */
proto.senml_protobuf.Record.prototype.getBasevalueoptionalCase = function() {
  return /** @type {proto.senml_protobuf.Record.BasevalueoptionalCase} */(jspb.Message.computeOneofCase(this, proto.senml_protobuf.Record.oneofGroups_[0]));
};

/**
 * @enum {number}
 */
proto.senml_protobuf.Record.BasesumoptionalCase = {
  BASESUMOPTIONAL_NOT_SET: 0,
  BASESUM: 6
};

/**
 * @return {proto.senml_protobuf.Record.BasesumoptionalCase}
 */
proto.senml_protobuf.Record.prototype.getBasesumoptionalCase = function() {
  return /** @type {proto.senml_protobuf.Record.BasesumoptionalCase} */(jspb.Message.computeOneofCase(this, proto.senml_protobuf.Record.oneofGroups_[1]));
};

/**
 * @enum {number}
 */
proto.senml_protobuf.Record.ValueoneofCase = {
  VALUEONEOF_NOT_SET: 0,
  VALUE: 11,
  STRINGVALUE: 12,
  DATAVALUE: 13,
  BOOLVALUE: 14
};

/**
 * @return {proto.senml_protobuf.Record.ValueoneofCase}
 */
proto.senml_protobuf.Record.prototype.getValueoneofCase = function() {
  return /** @type {proto.senml_protobuf.Record.ValueoneofCase} */(jspb.Message.computeOneofCase(this, proto.senml_protobuf.Record.oneofGroups_[2]));
};

/**
 * @enum {number}
 */
proto.senml_protobuf.Record.SumoptionalCase = {
  SUMOPTIONAL_NOT_SET: 0,
  SUM: 15
};

/**
 * @return {proto.senml_protobuf.Record.SumoptionalCase}
 */
proto.senml_protobuf.Record.prototype.getSumoptionalCase = function() {
  return /** @type {proto.senml_protobuf.Record.SumoptionalCase} */(jspb.Message.computeOneofCase(this, proto.senml_protobuf.Record.oneofGroups_[3]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.senml_protobuf.Record.prototype.toObject = function(opt_includeInstance) {
  return proto.senml_protobuf.Record.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.senml_protobuf.Record} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.senml_protobuf.Record.toObject = function(includeInstance, msg) {
  var f, obj = {
    basename: jspb.Message.getFieldWithDefault(msg, 1, ""),
    basetime: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
    baseunit: jspb.Message.getFieldWithDefault(msg, 3, ""),
    baseversion: jspb.Message.getFieldWithDefault(msg, 4, 0),
    basevalue: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
    basesum: jspb.Message.getFloatingPointFieldWithDefault(msg, 6, 0.0),
    name: jspb.Message.getFieldWithDefault(msg, 7, ""),
    unit: jspb.Message.getFieldWithDefault(msg, 8, ""),
    time: jspb.Message.getFloatingPointFieldWithDefault(msg, 9, 0.0),
    updatetime: jspb.Message.getFloatingPointFieldWithDefault(msg, 10, 0.0),
    value: jspb.Message.getFloatingPointFieldWithDefault(msg, 11, 0.0),
    stringvalue: jspb.Message.getFieldWithDefault(msg, 12, ""),
    datavalue: jspb.Message.getFieldWithDefault(msg, 13, ""),
    boolvalue: jspb.Message.getBooleanFieldWithDefault(msg, 14, false),
    sum: jspb.Message.getFloatingPointFieldWithDefault(msg, 15, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.senml_protobuf.Record}
 */
proto.senml_protobuf.Record.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.senml_protobuf.Record;
  return proto.senml_protobuf.Record.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.senml_protobuf.Record} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.senml_protobuf.Record}
 */
proto.senml_protobuf.Record.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setBasename(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setBasetime(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setBaseunit(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setBaseversion(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setBasevalue(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setBasesum(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setUnit(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setTime(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setUpdatetime(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setValue(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setStringvalue(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setDatavalue(value);
      break;
    case 14:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setBoolvalue(value);
      break;
    case 15:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setSum(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.senml_protobuf.Record.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.senml_protobuf.Record.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.senml_protobuf.Record} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.senml_protobuf.Record.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBasename();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getBasetime();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
  f = message.getBaseunit();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getBaseversion();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeDouble(
      5,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeDouble(
      6,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getUnit();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getTime();
  if (f !== 0.0) {
    writer.writeDouble(
      9,
      f
    );
  }
  f = message.getUpdatetime();
  if (f !== 0.0) {
    writer.writeDouble(
      10,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 11));
  if (f != null) {
    writer.writeDouble(
      11,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 12));
  if (f != null) {
    writer.writeString(
      12,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 13));
  if (f != null) {
    writer.writeString(
      13,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 14));
  if (f != null) {
    writer.writeBool(
      14,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 15));
  if (f != null) {
    writer.writeDouble(
      15,
      f
    );
  }
};


/**
 * optional string baseName = 1;
 * @return {string}
 */
proto.senml_protobuf.Record.prototype.getBasename = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.senml_protobuf.Record} returns this
 */
proto.senml_protobuf.Record.prototype.setBasename = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional double baseTime = 2;
 * @return {number}
 */
proto.senml_protobuf.Record.prototype.getBasetime = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.senml_protobuf.Record} returns this
 */
proto.senml_protobuf.Record.prototype.setBasetime = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional string baseUnit = 3;
 * @return {string}
 */
proto.senml_protobuf.Record.prototype.getBaseunit = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.senml_protobuf.Record} returns this
 */
proto.senml_protobuf.Record.prototype.setBaseunit = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional int32 baseVersion = 4;
 * @return {number}
 */
proto.senml_protobuf.Record.prototype.getBaseversion = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.senml_protobuf.Record} returns this
 */
proto.senml_protobuf.Record.prototype.setBaseversion = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional double baseValue = 5;
 * @return {number}
 */
proto.senml_protobuf.Record.prototype.getBasevalue = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.senml_protobuf.Record} returns this
 */
proto.senml_protobuf.Record.prototype.setBasevalue = function(value) {
  return jspb.Message.setOneofField(this, 5, proto.senml_protobuf.Record.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.senml_protobuf.Record} returns this
 */
proto.senml_protobuf.Record.prototype.clearBasevalue = function() {
  return jspb.Message.setOneofField(this, 5, proto.senml_protobuf.Record.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.senml_protobuf.Record.prototype.hasBasevalue = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional double baseSum = 6;
 * @return {number}
 */
proto.senml_protobuf.Record.prototype.getBasesum = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.senml_protobuf.Record} returns this
 */
proto.senml_protobuf.Record.prototype.setBasesum = function(value) {
  return jspb.Message.setOneofField(this, 6, proto.senml_protobuf.Record.oneofGroups_[1], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.senml_protobuf.Record} returns this
 */
proto.senml_protobuf.Record.prototype.clearBasesum = function() {
  return jspb.Message.setOneofField(this, 6, proto.senml_protobuf.Record.oneofGroups_[1], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.senml_protobuf.Record.prototype.hasBasesum = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional string name = 7;
 * @return {string}
 */
proto.senml_protobuf.Record.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.senml_protobuf.Record} returns this
 */
proto.senml_protobuf.Record.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string unit = 8;
 * @return {string}
 */
proto.senml_protobuf.Record.prototype.getUnit = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.senml_protobuf.Record} returns this
 */
proto.senml_protobuf.Record.prototype.setUnit = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional double time = 9;
 * @return {number}
 */
proto.senml_protobuf.Record.prototype.getTime = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 9, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.senml_protobuf.Record} returns this
 */
proto.senml_protobuf.Record.prototype.setTime = function(value) {
  return jspb.Message.setProto3FloatField(this, 9, value);
};


/**
 * optional double updateTime = 10;
 * @return {number}
 */
proto.senml_protobuf.Record.prototype.getUpdatetime = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 10, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.senml_protobuf.Record} returns this
 */
proto.senml_protobuf.Record.prototype.setUpdatetime = function(value) {
  return jspb.Message.setProto3FloatField(this, 10, value);
};


/**
 * optional double value = 11;
 * @return {number}
 */
proto.senml_protobuf.Record.prototype.getValue = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 11, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.senml_protobuf.Record} returns this
 */
proto.senml_protobuf.Record.prototype.setValue = function(value) {
  return jspb.Message.setOneofField(this, 11, proto.senml_protobuf.Record.oneofGroups_[2], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.senml_protobuf.Record} returns this
 */
proto.senml_protobuf.Record.prototype.clearValue = function() {
  return jspb.Message.setOneofField(this, 11, proto.senml_protobuf.Record.oneofGroups_[2], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.senml_protobuf.Record.prototype.hasValue = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional string stringValue = 12;
 * @return {string}
 */
proto.senml_protobuf.Record.prototype.getStringvalue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/**
 * @param {string} value
 * @return {!proto.senml_protobuf.Record} returns this
 */
proto.senml_protobuf.Record.prototype.setStringvalue = function(value) {
  return jspb.Message.setOneofField(this, 12, proto.senml_protobuf.Record.oneofGroups_[2], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.senml_protobuf.Record} returns this
 */
proto.senml_protobuf.Record.prototype.clearStringvalue = function() {
  return jspb.Message.setOneofField(this, 12, proto.senml_protobuf.Record.oneofGroups_[2], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.senml_protobuf.Record.prototype.hasStringvalue = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional string dataValue = 13;
 * @return {string}
 */
proto.senml_protobuf.Record.prototype.getDatavalue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/**
 * @param {string} value
 * @return {!proto.senml_protobuf.Record} returns this
 */
proto.senml_protobuf.Record.prototype.setDatavalue = function(value) {
  return jspb.Message.setOneofField(this, 13, proto.senml_protobuf.Record.oneofGroups_[2], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.senml_protobuf.Record} returns this
 */
proto.senml_protobuf.Record.prototype.clearDatavalue = function() {
  return jspb.Message.setOneofField(this, 13, proto.senml_protobuf.Record.oneofGroups_[2], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.senml_protobuf.Record.prototype.hasDatavalue = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * optional bool boolValue = 14;
 * @return {boolean}
 */
proto.senml_protobuf.Record.prototype.getBoolvalue = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 14, false));
};


/**
 * @param {boolean} value
 * @return {!proto.senml_protobuf.Record} returns this
 */
proto.senml_protobuf.Record.prototype.setBoolvalue = function(value) {
  return jspb.Message.setOneofField(this, 14, proto.senml_protobuf.Record.oneofGroups_[2], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.senml_protobuf.Record} returns this
 */
proto.senml_protobuf.Record.prototype.clearBoolvalue = function() {
  return jspb.Message.setOneofField(this, 14, proto.senml_protobuf.Record.oneofGroups_[2], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.senml_protobuf.Record.prototype.hasBoolvalue = function() {
  return jspb.Message.getField(this, 14) != null;
};


/**
 * optional double sum = 15;
 * @return {number}
 */
proto.senml_protobuf.Record.prototype.getSum = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 15, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.senml_protobuf.Record} returns this
 */
proto.senml_protobuf.Record.prototype.setSum = function(value) {
  return jspb.Message.setOneofField(this, 15, proto.senml_protobuf.Record.oneofGroups_[3], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.senml_protobuf.Record} returns this
 */
proto.senml_protobuf.Record.prototype.clearSum = function() {
  return jspb.Message.setOneofField(this, 15, proto.senml_protobuf.Record.oneofGroups_[3], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.senml_protobuf.Record.prototype.hasSum = function() {
  return jspb.Message.getField(this, 15) != null;
};


