# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: senml.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("senml.proto", :syntax => :proto3) do
    add_message "senml_protobuf.Record" do
      optional :baseName, :string, 1
      optional :baseTime, :double, 2
      optional :baseUnit, :string, 3
      optional :baseVersion, :int32, 4
      optional :name, :string, 7
      optional :unit, :string, 8
      optional :time, :double, 9
      optional :updateTime, :double, 10
      oneof :baseValueOptional do
        optional :baseValue, :double, 5
      end
      oneof :baseSumOptional do
        optional :baseSum, :double, 6
      end
      oneof :valueOneof do
        optional :value, :double, 11
        optional :stringValue, :string, 12
        optional :dataValue, :string, 13
        optional :boolValue, :bool, 14
      end
      oneof :sumOptional do
        optional :sum, :double, 15
      end
    end
    add_message "senml_protobuf.Message" do
      repeated :pack, :message, 1, "senml_protobuf.Record"
    end
  end
end

module SenmlProtobuf
  Record = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("senml_protobuf.Record").msgclass
  Message = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("senml_protobuf.Message").msgclass
end
