# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: senml.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("senml.proto", :syntax => :proto3) do
    add_message "senml_proto.Record" do
      optional :baseName, :string, 1
      optional :baseTime, :double, 2
      optional :baseUnit, :string, 3
      optional :baseVersion, :int32, 4
      optional :baseValue, :double, 5
      optional :baseSum, :double, 6
      optional :name, :string, 7
      optional :unit, :string, 8
      optional :time, :double, 9
      optional :updateTime, :double, 16
      optional :value, :double, 10
      optional :stringValue, :string, 11
      optional :dataValue, :string, 12
      optional :boolValue, :bool, 13
      optional :sum, :double, 14
      optional :type, :enum, 15, "senml_proto.Record.ValueType"
    end
    add_enum "senml_proto.Record.ValueType" do
      value :FLOAT, 0
      value :STRING, 1
      value :BINARY, 2
      value :BOOL, 3
      value :SUM, 4
    end
  end
end

module SenmlProto
  Record = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("senml_proto.Record").msgclass
  Record::ValueType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("senml_proto.Record.ValueType").enummodule
end
