<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: senml.proto

namespace Senml_proto;

if (false) {
    /**
     * This class is deprecated. Use Senml_proto\Record\ValueType instead.
     * @deprecated
     */
    class Record_ValueType {}
}
class_exists(Record\ValueType::class);
@trigger_error('Senml_proto\Record_ValueType is deprecated and will be removed in the next major release. Use Senml_proto\Record\ValueType instead', E_USER_DEPRECATED);

