<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: senml.proto

namespace Senml_proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>senml_proto.Record</code>
 */
class Record extends \Google\Protobuf\Internal\Message
{
    /**
     * base meta fields
     *
     * Generated from protobuf field <code>string baseName = 1;</code>
     */
    protected $baseName = '';
    /**
     * Generated from protobuf field <code>double baseTime = 2;</code>
     */
    protected $baseTime = 0.0;
    /**
     * Generated from protobuf field <code>string baseUnit = 3;</code>
     */
    protected $baseUnit = '';
    /**
     * Generated from protobuf field <code>int32 baseVersion = 4;</code>
     */
    protected $baseVersion = 0;
    /**
     * Generated from protobuf field <code>double baseValue = 5;</code>
     */
    protected $baseValue = 0.0;
    /**
     * Generated from protobuf field <code>double baseSum = 6;</code>
     */
    protected $baseSum = 0.0;
    /**
     * meta fields
     *
     * Generated from protobuf field <code>string name = 7;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string unit = 8;</code>
     */
    protected $unit = '';
    /**
     * Generated from protobuf field <code>double time = 9;</code>
     */
    protected $time = 0.0;
    /**
     * rarely used
     *
     * Generated from protobuf field <code>double updateTime = 16;</code>
     */
    protected $updateTime = 0.0;
    /**
     * value fields
     *
     * Generated from protobuf field <code>double value = 10;</code>
     */
    protected $value = 0.0;
    /**
     * Generated from protobuf field <code>string stringValue = 11;</code>
     */
    protected $stringValue = '';
    /**
     * Generated from protobuf field <code>string dataValue = 12;</code>
     */
    protected $dataValue = '';
    /**
     * Generated from protobuf field <code>bool boolValue = 13;</code>
     */
    protected $boolValue = false;
    /**
     * Generated from protobuf field <code>double sum = 14;</code>
     */
    protected $sum = 0.0;
    /**
     * value type indicator
     *
     * Generated from protobuf field <code>.senml_proto.Record.ValueType type = 15;</code>
     */
    protected $type = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $baseName
     *           base meta fields
     *     @type float $baseTime
     *     @type string $baseUnit
     *     @type int $baseVersion
     *     @type float $baseValue
     *     @type float $baseSum
     *     @type string $name
     *           meta fields
     *     @type string $unit
     *     @type float $time
     *     @type float $updateTime
     *           rarely used
     *     @type float $value
     *           value fields
     *     @type string $stringValue
     *     @type string $dataValue
     *     @type bool $boolValue
     *     @type float $sum
     *     @type int $type
     *           value type indicator
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Senml::initOnce();
        parent::__construct($data);
    }

    /**
     * base meta fields
     *
     * Generated from protobuf field <code>string baseName = 1;</code>
     * @return string
     */
    public function getBaseName()
    {
        return $this->baseName;
    }

    /**
     * base meta fields
     *
     * Generated from protobuf field <code>string baseName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBaseName($var)
    {
        GPBUtil::checkString($var, True);
        $this->baseName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double baseTime = 2;</code>
     * @return float
     */
    public function getBaseTime()
    {
        return $this->baseTime;
    }

    /**
     * Generated from protobuf field <code>double baseTime = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setBaseTime($var)
    {
        GPBUtil::checkDouble($var);
        $this->baseTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string baseUnit = 3;</code>
     * @return string
     */
    public function getBaseUnit()
    {
        return $this->baseUnit;
    }

    /**
     * Generated from protobuf field <code>string baseUnit = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setBaseUnit($var)
    {
        GPBUtil::checkString($var, True);
        $this->baseUnit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 baseVersion = 4;</code>
     * @return int
     */
    public function getBaseVersion()
    {
        return $this->baseVersion;
    }

    /**
     * Generated from protobuf field <code>int32 baseVersion = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setBaseVersion($var)
    {
        GPBUtil::checkInt32($var);
        $this->baseVersion = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double baseValue = 5;</code>
     * @return float
     */
    public function getBaseValue()
    {
        return $this->baseValue;
    }

    /**
     * Generated from protobuf field <code>double baseValue = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setBaseValue($var)
    {
        GPBUtil::checkDouble($var);
        $this->baseValue = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double baseSum = 6;</code>
     * @return float
     */
    public function getBaseSum()
    {
        return $this->baseSum;
    }

    /**
     * Generated from protobuf field <code>double baseSum = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setBaseSum($var)
    {
        GPBUtil::checkDouble($var);
        $this->baseSum = $var;

        return $this;
    }

    /**
     * meta fields
     *
     * Generated from protobuf field <code>string name = 7;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * meta fields
     *
     * Generated from protobuf field <code>string name = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string unit = 8;</code>
     * @return string
     */
    public function getUnit()
    {
        return $this->unit;
    }

    /**
     * Generated from protobuf field <code>string unit = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setUnit($var)
    {
        GPBUtil::checkString($var, True);
        $this->unit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double time = 9;</code>
     * @return float
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     * Generated from protobuf field <code>double time = 9;</code>
     * @param float $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkDouble($var);
        $this->time = $var;

        return $this;
    }

    /**
     * rarely used
     *
     * Generated from protobuf field <code>double updateTime = 16;</code>
     * @return float
     */
    public function getUpdateTime()
    {
        return $this->updateTime;
    }

    /**
     * rarely used
     *
     * Generated from protobuf field <code>double updateTime = 16;</code>
     * @param float $var
     * @return $this
     */
    public function setUpdateTime($var)
    {
        GPBUtil::checkDouble($var);
        $this->updateTime = $var;

        return $this;
    }

    /**
     * value fields
     *
     * Generated from protobuf field <code>double value = 10;</code>
     * @return float
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * value fields
     *
     * Generated from protobuf field <code>double value = 10;</code>
     * @param float $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkDouble($var);
        $this->value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string stringValue = 11;</code>
     * @return string
     */
    public function getStringValue()
    {
        return $this->stringValue;
    }

    /**
     * Generated from protobuf field <code>string stringValue = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setStringValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->stringValue = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string dataValue = 12;</code>
     * @return string
     */
    public function getDataValue()
    {
        return $this->dataValue;
    }

    /**
     * Generated from protobuf field <code>string dataValue = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setDataValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->dataValue = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool boolValue = 13;</code>
     * @return bool
     */
    public function getBoolValue()
    {
        return $this->boolValue;
    }

    /**
     * Generated from protobuf field <code>bool boolValue = 13;</code>
     * @param bool $var
     * @return $this
     */
    public function setBoolValue($var)
    {
        GPBUtil::checkBool($var);
        $this->boolValue = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double sum = 14;</code>
     * @return float
     */
    public function getSum()
    {
        return $this->sum;
    }

    /**
     * Generated from protobuf field <code>double sum = 14;</code>
     * @param float $var
     * @return $this
     */
    public function setSum($var)
    {
        GPBUtil::checkDouble($var);
        $this->sum = $var;

        return $this;
    }

    /**
     * value type indicator
     *
     * Generated from protobuf field <code>.senml_proto.Record.ValueType type = 15;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * value type indicator
     *
     * Generated from protobuf field <code>.senml_proto.Record.ValueType type = 15;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Senml_proto\Record_ValueType::class);
        $this->type = $var;

        return $this;
    }

}

