// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: senml.proto

package senml_proto;

public final class Senml {
  private Senml() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RecordOrBuilder extends
      // @@protoc_insertion_point(interface_extends:senml_proto.Record)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * base meta fields
     * </pre>
     *
     * <code>string baseName = 1;</code>
     * @return The baseName.
     */
    java.lang.String getBaseName();
    /**
     * <pre>
     * base meta fields
     * </pre>
     *
     * <code>string baseName = 1;</code>
     * @return The bytes for baseName.
     */
    com.google.protobuf.ByteString
        getBaseNameBytes();

    /**
     * <code>double baseTime = 2;</code>
     * @return The baseTime.
     */
    double getBaseTime();

    /**
     * <code>string baseUnit = 3;</code>
     * @return The baseUnit.
     */
    java.lang.String getBaseUnit();
    /**
     * <code>string baseUnit = 3;</code>
     * @return The bytes for baseUnit.
     */
    com.google.protobuf.ByteString
        getBaseUnitBytes();

    /**
     * <code>int32 baseVersion = 4;</code>
     * @return The baseVersion.
     */
    int getBaseVersion();

    /**
     * <code>double baseValue = 5;</code>
     * @return The baseValue.
     */
    double getBaseValue();

    /**
     * <code>double baseSum = 6;</code>
     * @return The baseSum.
     */
    double getBaseSum();

    /**
     * <pre>
     * meta fields
     * </pre>
     *
     * <code>string name = 7;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <pre>
     * meta fields
     * </pre>
     *
     * <code>string name = 7;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string unit = 8;</code>
     * @return The unit.
     */
    java.lang.String getUnit();
    /**
     * <code>string unit = 8;</code>
     * @return The bytes for unit.
     */
    com.google.protobuf.ByteString
        getUnitBytes();

    /**
     * <code>double time = 9;</code>
     * @return The time.
     */
    double getTime();

    /**
     * <pre>
     * rarely used
     * </pre>
     *
     * <code>double updateTime = 16;</code>
     * @return The updateTime.
     */
    double getUpdateTime();

    /**
     * <pre>
     * value fields
     * </pre>
     *
     * <code>double value = 10;</code>
     * @return The value.
     */
    double getValue();

    /**
     * <code>string stringValue = 11;</code>
     * @return The stringValue.
     */
    java.lang.String getStringValue();
    /**
     * <code>string stringValue = 11;</code>
     * @return The bytes for stringValue.
     */
    com.google.protobuf.ByteString
        getStringValueBytes();

    /**
     * <code>string dataValue = 12;</code>
     * @return The dataValue.
     */
    java.lang.String getDataValue();
    /**
     * <code>string dataValue = 12;</code>
     * @return The bytes for dataValue.
     */
    com.google.protobuf.ByteString
        getDataValueBytes();

    /**
     * <code>bool boolValue = 13;</code>
     * @return The boolValue.
     */
    boolean getBoolValue();

    /**
     * <code>double sum = 14;</code>
     * @return The sum.
     */
    double getSum();

    /**
     * <pre>
     * value type indicator
     * </pre>
     *
     * <code>.senml_proto.Record.ValueType type = 15;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <pre>
     * value type indicator
     * </pre>
     *
     * <code>.senml_proto.Record.ValueType type = 15;</code>
     * @return The type.
     */
    senml_proto.Senml.Record.ValueType getType();
  }
  /**
   * Protobuf type {@code senml_proto.Record}
   */
  public  static final class Record extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:senml_proto.Record)
      RecordOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Record.newBuilder() to construct.
    private Record(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Record() {
      baseName_ = "";
      baseUnit_ = "";
      name_ = "";
      unit_ = "";
      stringValue_ = "";
      dataValue_ = "";
      type_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Record();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Record(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              baseName_ = s;
              break;
            }
            case 17: {

              baseTime_ = input.readDouble();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              baseUnit_ = s;
              break;
            }
            case 32: {

              baseVersion_ = input.readInt32();
              break;
            }
            case 41: {

              baseValue_ = input.readDouble();
              break;
            }
            case 49: {

              baseSum_ = input.readDouble();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              unit_ = s;
              break;
            }
            case 73: {

              time_ = input.readDouble();
              break;
            }
            case 81: {

              value_ = input.readDouble();
              break;
            }
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();

              stringValue_ = s;
              break;
            }
            case 98: {
              java.lang.String s = input.readStringRequireUtf8();

              dataValue_ = s;
              break;
            }
            case 104: {

              boolValue_ = input.readBool();
              break;
            }
            case 113: {

              sum_ = input.readDouble();
              break;
            }
            case 120: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 129: {

              updateTime_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return senml_proto.Senml.internal_static_senml_proto_Record_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return senml_proto.Senml.internal_static_senml_proto_Record_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              senml_proto.Senml.Record.class, senml_proto.Senml.Record.Builder.class);
    }

    /**
     * Protobuf enum {@code senml_proto.Record.ValueType}
     */
    public enum ValueType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>FLOAT = 0;</code>
       */
      FLOAT(0),
      /**
       * <code>STRING = 1;</code>
       */
      STRING(1),
      /**
       * <code>BINARY = 2;</code>
       */
      BINARY(2),
      /**
       * <code>BOOL = 3;</code>
       */
      BOOL(3),
      /**
       * <code>SUM = 4;</code>
       */
      SUM(4),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>FLOAT = 0;</code>
       */
      public static final int FLOAT_VALUE = 0;
      /**
       * <code>STRING = 1;</code>
       */
      public static final int STRING_VALUE = 1;
      /**
       * <code>BINARY = 2;</code>
       */
      public static final int BINARY_VALUE = 2;
      /**
       * <code>BOOL = 3;</code>
       */
      public static final int BOOL_VALUE = 3;
      /**
       * <code>SUM = 4;</code>
       */
      public static final int SUM_VALUE = 4;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ValueType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static ValueType forNumber(int value) {
        switch (value) {
          case 0: return FLOAT;
          case 1: return STRING;
          case 2: return BINARY;
          case 3: return BOOL;
          case 4: return SUM;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ValueType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ValueType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ValueType>() {
              public ValueType findValueByNumber(int number) {
                return ValueType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return senml_proto.Senml.Record.getDescriptor().getEnumTypes().get(0);
      }

      private static final ValueType[] VALUES = values();

      public static ValueType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ValueType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:senml_proto.Record.ValueType)
    }

    public static final int BASENAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object baseName_;
    /**
     * <pre>
     * base meta fields
     * </pre>
     *
     * <code>string baseName = 1;</code>
     * @return The baseName.
     */
    public java.lang.String getBaseName() {
      java.lang.Object ref = baseName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        baseName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * base meta fields
     * </pre>
     *
     * <code>string baseName = 1;</code>
     * @return The bytes for baseName.
     */
    public com.google.protobuf.ByteString
        getBaseNameBytes() {
      java.lang.Object ref = baseName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        baseName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BASETIME_FIELD_NUMBER = 2;
    private double baseTime_;
    /**
     * <code>double baseTime = 2;</code>
     * @return The baseTime.
     */
    public double getBaseTime() {
      return baseTime_;
    }

    public static final int BASEUNIT_FIELD_NUMBER = 3;
    private volatile java.lang.Object baseUnit_;
    /**
     * <code>string baseUnit = 3;</code>
     * @return The baseUnit.
     */
    public java.lang.String getBaseUnit() {
      java.lang.Object ref = baseUnit_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        baseUnit_ = s;
        return s;
      }
    }
    /**
     * <code>string baseUnit = 3;</code>
     * @return The bytes for baseUnit.
     */
    public com.google.protobuf.ByteString
        getBaseUnitBytes() {
      java.lang.Object ref = baseUnit_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        baseUnit_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BASEVERSION_FIELD_NUMBER = 4;
    private int baseVersion_;
    /**
     * <code>int32 baseVersion = 4;</code>
     * @return The baseVersion.
     */
    public int getBaseVersion() {
      return baseVersion_;
    }

    public static final int BASEVALUE_FIELD_NUMBER = 5;
    private double baseValue_;
    /**
     * <code>double baseValue = 5;</code>
     * @return The baseValue.
     */
    public double getBaseValue() {
      return baseValue_;
    }

    public static final int BASESUM_FIELD_NUMBER = 6;
    private double baseSum_;
    /**
     * <code>double baseSum = 6;</code>
     * @return The baseSum.
     */
    public double getBaseSum() {
      return baseSum_;
    }

    public static final int NAME_FIELD_NUMBER = 7;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     * meta fields
     * </pre>
     *
     * <code>string name = 7;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * meta fields
     * </pre>
     *
     * <code>string name = 7;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UNIT_FIELD_NUMBER = 8;
    private volatile java.lang.Object unit_;
    /**
     * <code>string unit = 8;</code>
     * @return The unit.
     */
    public java.lang.String getUnit() {
      java.lang.Object ref = unit_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        unit_ = s;
        return s;
      }
    }
    /**
     * <code>string unit = 8;</code>
     * @return The bytes for unit.
     */
    public com.google.protobuf.ByteString
        getUnitBytes() {
      java.lang.Object ref = unit_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        unit_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_FIELD_NUMBER = 9;
    private double time_;
    /**
     * <code>double time = 9;</code>
     * @return The time.
     */
    public double getTime() {
      return time_;
    }

    public static final int UPDATETIME_FIELD_NUMBER = 16;
    private double updateTime_;
    /**
     * <pre>
     * rarely used
     * </pre>
     *
     * <code>double updateTime = 16;</code>
     * @return The updateTime.
     */
    public double getUpdateTime() {
      return updateTime_;
    }

    public static final int VALUE_FIELD_NUMBER = 10;
    private double value_;
    /**
     * <pre>
     * value fields
     * </pre>
     *
     * <code>double value = 10;</code>
     * @return The value.
     */
    public double getValue() {
      return value_;
    }

    public static final int STRINGVALUE_FIELD_NUMBER = 11;
    private volatile java.lang.Object stringValue_;
    /**
     * <code>string stringValue = 11;</code>
     * @return The stringValue.
     */
    public java.lang.String getStringValue() {
      java.lang.Object ref = stringValue_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stringValue_ = s;
        return s;
      }
    }
    /**
     * <code>string stringValue = 11;</code>
     * @return The bytes for stringValue.
     */
    public com.google.protobuf.ByteString
        getStringValueBytes() {
      java.lang.Object ref = stringValue_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stringValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATAVALUE_FIELD_NUMBER = 12;
    private volatile java.lang.Object dataValue_;
    /**
     * <code>string dataValue = 12;</code>
     * @return The dataValue.
     */
    public java.lang.String getDataValue() {
      java.lang.Object ref = dataValue_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dataValue_ = s;
        return s;
      }
    }
    /**
     * <code>string dataValue = 12;</code>
     * @return The bytes for dataValue.
     */
    public com.google.protobuf.ByteString
        getDataValueBytes() {
      java.lang.Object ref = dataValue_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BOOLVALUE_FIELD_NUMBER = 13;
    private boolean boolValue_;
    /**
     * <code>bool boolValue = 13;</code>
     * @return The boolValue.
     */
    public boolean getBoolValue() {
      return boolValue_;
    }

    public static final int SUM_FIELD_NUMBER = 14;
    private double sum_;
    /**
     * <code>double sum = 14;</code>
     * @return The sum.
     */
    public double getSum() {
      return sum_;
    }

    public static final int TYPE_FIELD_NUMBER = 15;
    private int type_;
    /**
     * <pre>
     * value type indicator
     * </pre>
     *
     * <code>.senml_proto.Record.ValueType type = 15;</code>
     * @return The enum numeric value on the wire for type.
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * value type indicator
     * </pre>
     *
     * <code>.senml_proto.Record.ValueType type = 15;</code>
     * @return The type.
     */
    public senml_proto.Senml.Record.ValueType getType() {
      @SuppressWarnings("deprecation")
      senml_proto.Senml.Record.ValueType result = senml_proto.Senml.Record.ValueType.valueOf(type_);
      return result == null ? senml_proto.Senml.Record.ValueType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getBaseNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, baseName_);
      }
      if (baseTime_ != 0D) {
        output.writeDouble(2, baseTime_);
      }
      if (!getBaseUnitBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, baseUnit_);
      }
      if (baseVersion_ != 0) {
        output.writeInt32(4, baseVersion_);
      }
      if (baseValue_ != 0D) {
        output.writeDouble(5, baseValue_);
      }
      if (baseSum_ != 0D) {
        output.writeDouble(6, baseSum_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, name_);
      }
      if (!getUnitBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, unit_);
      }
      if (time_ != 0D) {
        output.writeDouble(9, time_);
      }
      if (value_ != 0D) {
        output.writeDouble(10, value_);
      }
      if (!getStringValueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, stringValue_);
      }
      if (!getDataValueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, dataValue_);
      }
      if (boolValue_ != false) {
        output.writeBool(13, boolValue_);
      }
      if (sum_ != 0D) {
        output.writeDouble(14, sum_);
      }
      if (type_ != senml_proto.Senml.Record.ValueType.FLOAT.getNumber()) {
        output.writeEnum(15, type_);
      }
      if (updateTime_ != 0D) {
        output.writeDouble(16, updateTime_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getBaseNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, baseName_);
      }
      if (baseTime_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, baseTime_);
      }
      if (!getBaseUnitBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, baseUnit_);
      }
      if (baseVersion_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, baseVersion_);
      }
      if (baseValue_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, baseValue_);
      }
      if (baseSum_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, baseSum_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, name_);
      }
      if (!getUnitBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, unit_);
      }
      if (time_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(9, time_);
      }
      if (value_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(10, value_);
      }
      if (!getStringValueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, stringValue_);
      }
      if (!getDataValueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, dataValue_);
      }
      if (boolValue_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(13, boolValue_);
      }
      if (sum_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(14, sum_);
      }
      if (type_ != senml_proto.Senml.Record.ValueType.FLOAT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(15, type_);
      }
      if (updateTime_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(16, updateTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof senml_proto.Senml.Record)) {
        return super.equals(obj);
      }
      senml_proto.Senml.Record other = (senml_proto.Senml.Record) obj;

      if (!getBaseName()
          .equals(other.getBaseName())) return false;
      if (java.lang.Double.doubleToLongBits(getBaseTime())
          != java.lang.Double.doubleToLongBits(
              other.getBaseTime())) return false;
      if (!getBaseUnit()
          .equals(other.getBaseUnit())) return false;
      if (getBaseVersion()
          != other.getBaseVersion()) return false;
      if (java.lang.Double.doubleToLongBits(getBaseValue())
          != java.lang.Double.doubleToLongBits(
              other.getBaseValue())) return false;
      if (java.lang.Double.doubleToLongBits(getBaseSum())
          != java.lang.Double.doubleToLongBits(
              other.getBaseSum())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getUnit()
          .equals(other.getUnit())) return false;
      if (java.lang.Double.doubleToLongBits(getTime())
          != java.lang.Double.doubleToLongBits(
              other.getTime())) return false;
      if (java.lang.Double.doubleToLongBits(getUpdateTime())
          != java.lang.Double.doubleToLongBits(
              other.getUpdateTime())) return false;
      if (java.lang.Double.doubleToLongBits(getValue())
          != java.lang.Double.doubleToLongBits(
              other.getValue())) return false;
      if (!getStringValue()
          .equals(other.getStringValue())) return false;
      if (!getDataValue()
          .equals(other.getDataValue())) return false;
      if (getBoolValue()
          != other.getBoolValue()) return false;
      if (java.lang.Double.doubleToLongBits(getSum())
          != java.lang.Double.doubleToLongBits(
              other.getSum())) return false;
      if (type_ != other.type_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BASENAME_FIELD_NUMBER;
      hash = (53 * hash) + getBaseName().hashCode();
      hash = (37 * hash) + BASETIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getBaseTime()));
      hash = (37 * hash) + BASEUNIT_FIELD_NUMBER;
      hash = (53 * hash) + getBaseUnit().hashCode();
      hash = (37 * hash) + BASEVERSION_FIELD_NUMBER;
      hash = (53 * hash) + getBaseVersion();
      hash = (37 * hash) + BASEVALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getBaseValue()));
      hash = (37 * hash) + BASESUM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getBaseSum()));
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + UNIT_FIELD_NUMBER;
      hash = (53 * hash) + getUnit().hashCode();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getTime()));
      hash = (37 * hash) + UPDATETIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getUpdateTime()));
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getValue()));
      hash = (37 * hash) + STRINGVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getStringValue().hashCode();
      hash = (37 * hash) + DATAVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getDataValue().hashCode();
      hash = (37 * hash) + BOOLVALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getBoolValue());
      hash = (37 * hash) + SUM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getSum()));
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static senml_proto.Senml.Record parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static senml_proto.Senml.Record parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static senml_proto.Senml.Record parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static senml_proto.Senml.Record parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static senml_proto.Senml.Record parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static senml_proto.Senml.Record parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static senml_proto.Senml.Record parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static senml_proto.Senml.Record parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static senml_proto.Senml.Record parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static senml_proto.Senml.Record parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static senml_proto.Senml.Record parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static senml_proto.Senml.Record parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(senml_proto.Senml.Record prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code senml_proto.Record}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:senml_proto.Record)
        senml_proto.Senml.RecordOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return senml_proto.Senml.internal_static_senml_proto_Record_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return senml_proto.Senml.internal_static_senml_proto_Record_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                senml_proto.Senml.Record.class, senml_proto.Senml.Record.Builder.class);
      }

      // Construct using senml_proto.Senml.Record.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        baseName_ = "";

        baseTime_ = 0D;

        baseUnit_ = "";

        baseVersion_ = 0;

        baseValue_ = 0D;

        baseSum_ = 0D;

        name_ = "";

        unit_ = "";

        time_ = 0D;

        updateTime_ = 0D;

        value_ = 0D;

        stringValue_ = "";

        dataValue_ = "";

        boolValue_ = false;

        sum_ = 0D;

        type_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return senml_proto.Senml.internal_static_senml_proto_Record_descriptor;
      }

      @java.lang.Override
      public senml_proto.Senml.Record getDefaultInstanceForType() {
        return senml_proto.Senml.Record.getDefaultInstance();
      }

      @java.lang.Override
      public senml_proto.Senml.Record build() {
        senml_proto.Senml.Record result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public senml_proto.Senml.Record buildPartial() {
        senml_proto.Senml.Record result = new senml_proto.Senml.Record(this);
        result.baseName_ = baseName_;
        result.baseTime_ = baseTime_;
        result.baseUnit_ = baseUnit_;
        result.baseVersion_ = baseVersion_;
        result.baseValue_ = baseValue_;
        result.baseSum_ = baseSum_;
        result.name_ = name_;
        result.unit_ = unit_;
        result.time_ = time_;
        result.updateTime_ = updateTime_;
        result.value_ = value_;
        result.stringValue_ = stringValue_;
        result.dataValue_ = dataValue_;
        result.boolValue_ = boolValue_;
        result.sum_ = sum_;
        result.type_ = type_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof senml_proto.Senml.Record) {
          return mergeFrom((senml_proto.Senml.Record)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(senml_proto.Senml.Record other) {
        if (other == senml_proto.Senml.Record.getDefaultInstance()) return this;
        if (!other.getBaseName().isEmpty()) {
          baseName_ = other.baseName_;
          onChanged();
        }
        if (other.getBaseTime() != 0D) {
          setBaseTime(other.getBaseTime());
        }
        if (!other.getBaseUnit().isEmpty()) {
          baseUnit_ = other.baseUnit_;
          onChanged();
        }
        if (other.getBaseVersion() != 0) {
          setBaseVersion(other.getBaseVersion());
        }
        if (other.getBaseValue() != 0D) {
          setBaseValue(other.getBaseValue());
        }
        if (other.getBaseSum() != 0D) {
          setBaseSum(other.getBaseSum());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getUnit().isEmpty()) {
          unit_ = other.unit_;
          onChanged();
        }
        if (other.getTime() != 0D) {
          setTime(other.getTime());
        }
        if (other.getUpdateTime() != 0D) {
          setUpdateTime(other.getUpdateTime());
        }
        if (other.getValue() != 0D) {
          setValue(other.getValue());
        }
        if (!other.getStringValue().isEmpty()) {
          stringValue_ = other.stringValue_;
          onChanged();
        }
        if (!other.getDataValue().isEmpty()) {
          dataValue_ = other.dataValue_;
          onChanged();
        }
        if (other.getBoolValue() != false) {
          setBoolValue(other.getBoolValue());
        }
        if (other.getSum() != 0D) {
          setSum(other.getSum());
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        senml_proto.Senml.Record parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (senml_proto.Senml.Record) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object baseName_ = "";
      /**
       * <pre>
       * base meta fields
       * </pre>
       *
       * <code>string baseName = 1;</code>
       * @return The baseName.
       */
      public java.lang.String getBaseName() {
        java.lang.Object ref = baseName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          baseName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * base meta fields
       * </pre>
       *
       * <code>string baseName = 1;</code>
       * @return The bytes for baseName.
       */
      public com.google.protobuf.ByteString
          getBaseNameBytes() {
        java.lang.Object ref = baseName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          baseName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * base meta fields
       * </pre>
       *
       * <code>string baseName = 1;</code>
       * @param value The baseName to set.
       * @return This builder for chaining.
       */
      public Builder setBaseName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        baseName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * base meta fields
       * </pre>
       *
       * <code>string baseName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBaseName() {
        
        baseName_ = getDefaultInstance().getBaseName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * base meta fields
       * </pre>
       *
       * <code>string baseName = 1;</code>
       * @param value The bytes for baseName to set.
       * @return This builder for chaining.
       */
      public Builder setBaseNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        baseName_ = value;
        onChanged();
        return this;
      }

      private double baseTime_ ;
      /**
       * <code>double baseTime = 2;</code>
       * @return The baseTime.
       */
      public double getBaseTime() {
        return baseTime_;
      }
      /**
       * <code>double baseTime = 2;</code>
       * @param value The baseTime to set.
       * @return This builder for chaining.
       */
      public Builder setBaseTime(double value) {
        
        baseTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double baseTime = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBaseTime() {
        
        baseTime_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object baseUnit_ = "";
      /**
       * <code>string baseUnit = 3;</code>
       * @return The baseUnit.
       */
      public java.lang.String getBaseUnit() {
        java.lang.Object ref = baseUnit_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          baseUnit_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string baseUnit = 3;</code>
       * @return The bytes for baseUnit.
       */
      public com.google.protobuf.ByteString
          getBaseUnitBytes() {
        java.lang.Object ref = baseUnit_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          baseUnit_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string baseUnit = 3;</code>
       * @param value The baseUnit to set.
       * @return This builder for chaining.
       */
      public Builder setBaseUnit(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        baseUnit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string baseUnit = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearBaseUnit() {
        
        baseUnit_ = getDefaultInstance().getBaseUnit();
        onChanged();
        return this;
      }
      /**
       * <code>string baseUnit = 3;</code>
       * @param value The bytes for baseUnit to set.
       * @return This builder for chaining.
       */
      public Builder setBaseUnitBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        baseUnit_ = value;
        onChanged();
        return this;
      }

      private int baseVersion_ ;
      /**
       * <code>int32 baseVersion = 4;</code>
       * @return The baseVersion.
       */
      public int getBaseVersion() {
        return baseVersion_;
      }
      /**
       * <code>int32 baseVersion = 4;</code>
       * @param value The baseVersion to set.
       * @return This builder for chaining.
       */
      public Builder setBaseVersion(int value) {
        
        baseVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 baseVersion = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearBaseVersion() {
        
        baseVersion_ = 0;
        onChanged();
        return this;
      }

      private double baseValue_ ;
      /**
       * <code>double baseValue = 5;</code>
       * @return The baseValue.
       */
      public double getBaseValue() {
        return baseValue_;
      }
      /**
       * <code>double baseValue = 5;</code>
       * @param value The baseValue to set.
       * @return This builder for chaining.
       */
      public Builder setBaseValue(double value) {
        
        baseValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double baseValue = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearBaseValue() {
        
        baseValue_ = 0D;
        onChanged();
        return this;
      }

      private double baseSum_ ;
      /**
       * <code>double baseSum = 6;</code>
       * @return The baseSum.
       */
      public double getBaseSum() {
        return baseSum_;
      }
      /**
       * <code>double baseSum = 6;</code>
       * @param value The baseSum to set.
       * @return This builder for chaining.
       */
      public Builder setBaseSum(double value) {
        
        baseSum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double baseSum = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearBaseSum() {
        
        baseSum_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <pre>
       * meta fields
       * </pre>
       *
       * <code>string name = 7;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * meta fields
       * </pre>
       *
       * <code>string name = 7;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * meta fields
       * </pre>
       *
       * <code>string name = 7;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * meta fields
       * </pre>
       *
       * <code>string name = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * meta fields
       * </pre>
       *
       * <code>string name = 7;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object unit_ = "";
      /**
       * <code>string unit = 8;</code>
       * @return The unit.
       */
      public java.lang.String getUnit() {
        java.lang.Object ref = unit_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          unit_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string unit = 8;</code>
       * @return The bytes for unit.
       */
      public com.google.protobuf.ByteString
          getUnitBytes() {
        java.lang.Object ref = unit_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          unit_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string unit = 8;</code>
       * @param value The unit to set.
       * @return This builder for chaining.
       */
      public Builder setUnit(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        unit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string unit = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearUnit() {
        
        unit_ = getDefaultInstance().getUnit();
        onChanged();
        return this;
      }
      /**
       * <code>string unit = 8;</code>
       * @param value The bytes for unit to set.
       * @return This builder for chaining.
       */
      public Builder setUnitBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        unit_ = value;
        onChanged();
        return this;
      }

      private double time_ ;
      /**
       * <code>double time = 9;</code>
       * @return The time.
       */
      public double getTime() {
        return time_;
      }
      /**
       * <code>double time = 9;</code>
       * @param value The time to set.
       * @return This builder for chaining.
       */
      public Builder setTime(double value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double time = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearTime() {
        
        time_ = 0D;
        onChanged();
        return this;
      }

      private double updateTime_ ;
      /**
       * <pre>
       * rarely used
       * </pre>
       *
       * <code>double updateTime = 16;</code>
       * @return The updateTime.
       */
      public double getUpdateTime() {
        return updateTime_;
      }
      /**
       * <pre>
       * rarely used
       * </pre>
       *
       * <code>double updateTime = 16;</code>
       * @param value The updateTime to set.
       * @return This builder for chaining.
       */
      public Builder setUpdateTime(double value) {
        
        updateTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * rarely used
       * </pre>
       *
       * <code>double updateTime = 16;</code>
       * @return This builder for chaining.
       */
      public Builder clearUpdateTime() {
        
        updateTime_ = 0D;
        onChanged();
        return this;
      }

      private double value_ ;
      /**
       * <pre>
       * value fields
       * </pre>
       *
       * <code>double value = 10;</code>
       * @return The value.
       */
      public double getValue() {
        return value_;
      }
      /**
       * <pre>
       * value fields
       * </pre>
       *
       * <code>double value = 10;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(double value) {
        
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * value fields
       * </pre>
       *
       * <code>double value = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        
        value_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object stringValue_ = "";
      /**
       * <code>string stringValue = 11;</code>
       * @return The stringValue.
       */
      public java.lang.String getStringValue() {
        java.lang.Object ref = stringValue_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          stringValue_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string stringValue = 11;</code>
       * @return The bytes for stringValue.
       */
      public com.google.protobuf.ByteString
          getStringValueBytes() {
        java.lang.Object ref = stringValue_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stringValue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string stringValue = 11;</code>
       * @param value The stringValue to set.
       * @return This builder for chaining.
       */
      public Builder setStringValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        stringValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string stringValue = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearStringValue() {
        
        stringValue_ = getDefaultInstance().getStringValue();
        onChanged();
        return this;
      }
      /**
       * <code>string stringValue = 11;</code>
       * @param value The bytes for stringValue to set.
       * @return This builder for chaining.
       */
      public Builder setStringValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        stringValue_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dataValue_ = "";
      /**
       * <code>string dataValue = 12;</code>
       * @return The dataValue.
       */
      public java.lang.String getDataValue() {
        java.lang.Object ref = dataValue_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dataValue_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string dataValue = 12;</code>
       * @return The bytes for dataValue.
       */
      public com.google.protobuf.ByteString
          getDataValueBytes() {
        java.lang.Object ref = dataValue_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dataValue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string dataValue = 12;</code>
       * @param value The dataValue to set.
       * @return This builder for chaining.
       */
      public Builder setDataValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dataValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string dataValue = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearDataValue() {
        
        dataValue_ = getDefaultInstance().getDataValue();
        onChanged();
        return this;
      }
      /**
       * <code>string dataValue = 12;</code>
       * @param value The bytes for dataValue to set.
       * @return This builder for chaining.
       */
      public Builder setDataValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dataValue_ = value;
        onChanged();
        return this;
      }

      private boolean boolValue_ ;
      /**
       * <code>bool boolValue = 13;</code>
       * @return The boolValue.
       */
      public boolean getBoolValue() {
        return boolValue_;
      }
      /**
       * <code>bool boolValue = 13;</code>
       * @param value The boolValue to set.
       * @return This builder for chaining.
       */
      public Builder setBoolValue(boolean value) {
        
        boolValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool boolValue = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearBoolValue() {
        
        boolValue_ = false;
        onChanged();
        return this;
      }

      private double sum_ ;
      /**
       * <code>double sum = 14;</code>
       * @return The sum.
       */
      public double getSum() {
        return sum_;
      }
      /**
       * <code>double sum = 14;</code>
       * @param value The sum to set.
       * @return This builder for chaining.
       */
      public Builder setSum(double value) {
        
        sum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double sum = 14;</code>
       * @return This builder for chaining.
       */
      public Builder clearSum() {
        
        sum_ = 0D;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <pre>
       * value type indicator
       * </pre>
       *
       * <code>.senml_proto.Record.ValueType type = 15;</code>
       * @return The enum numeric value on the wire for type.
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <pre>
       * value type indicator
       * </pre>
       *
       * <code>.senml_proto.Record.ValueType type = 15;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * value type indicator
       * </pre>
       *
       * <code>.senml_proto.Record.ValueType type = 15;</code>
       * @return The type.
       */
      public senml_proto.Senml.Record.ValueType getType() {
        @SuppressWarnings("deprecation")
        senml_proto.Senml.Record.ValueType result = senml_proto.Senml.Record.ValueType.valueOf(type_);
        return result == null ? senml_proto.Senml.Record.ValueType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * value type indicator
       * </pre>
       *
       * <code>.senml_proto.Record.ValueType type = 15;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(senml_proto.Senml.Record.ValueType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * value type indicator
       * </pre>
       *
       * <code>.senml_proto.Record.ValueType type = 15;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:senml_proto.Record)
    }

    // @@protoc_insertion_point(class_scope:senml_proto.Record)
    private static final senml_proto.Senml.Record DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new senml_proto.Senml.Record();
    }

    public static senml_proto.Senml.Record getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Record>
        PARSER = new com.google.protobuf.AbstractParser<Record>() {
      @java.lang.Override
      public Record parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Record(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Record> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Record> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public senml_proto.Senml.Record getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_senml_proto_Record_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_senml_proto_Record_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013senml.proto\022\013senml_proto\"\374\002\n\006Record\022\020\n" +
      "\010baseName\030\001 \001(\t\022\020\n\010baseTime\030\002 \001(\001\022\020\n\010bas" +
      "eUnit\030\003 \001(\t\022\023\n\013baseVersion\030\004 \001(\005\022\021\n\tbase" +
      "Value\030\005 \001(\001\022\017\n\007baseSum\030\006 \001(\001\022\014\n\004name\030\007 \001" +
      "(\t\022\014\n\004unit\030\010 \001(\t\022\014\n\004time\030\t \001(\001\022\022\n\nupdate" +
      "Time\030\020 \001(\001\022\r\n\005value\030\n \001(\001\022\023\n\013stringValue" +
      "\030\013 \001(\t\022\021\n\tdataValue\030\014 \001(\t\022\021\n\tboolValue\030\r" +
      " \001(\010\022\013\n\003sum\030\016 \001(\001\022+\n\004type\030\017 \001(\0162\035.senml_" +
      "proto.Record.ValueType\"A\n\tValueType\022\t\n\005F" +
      "LOAT\020\000\022\n\n\006STRING\020\001\022\n\n\006BINARY\020\002\022\010\n\004BOOL\020\003" +
      "\022\007\n\003SUM\020\004b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_senml_proto_Record_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_senml_proto_Record_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_senml_proto_Record_descriptor,
        new java.lang.String[] { "BaseName", "BaseTime", "BaseUnit", "BaseVersion", "BaseValue", "BaseSum", "Name", "Unit", "Time", "UpdateTime", "Value", "StringValue", "DataValue", "BoolValue", "Sum", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
