<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: senml.proto

namespace Senml_protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * this contains the senml pack (array of records)
 *
 * Generated from protobuf message <code>senml_protobuf.Message</code>
 */
class Message extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .senml_protobuf.Record pack = 1;</code>
     */
    private $pack;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Senml_protobuf\Record[]|\Google\Protobuf\Internal\RepeatedField $pack
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Senml::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .senml_protobuf.Record pack = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPack()
    {
        return $this->pack;
    }

    /**
     * Generated from protobuf field <code>repeated .senml_protobuf.Record pack = 1;</code>
     * @param \Senml_protobuf\Record[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPack($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Senml_protobuf\Record::class);
        $this->pack = $arr;

        return $this;
    }

}

