name: CI

on: [push]
env: 
  LANGS: cpp python java js csharp ruby php go
  PROTO_FILE: senml.proto

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[automated]')"

    steps:
    - uses: actions/checkout@v1
    - name: Install Protoc
      uses: Arduino/actions/setup-protoc@master
    # Protoc Plugin: Go
    - name: Install Go
      uses: actions/setup-go@v1
    - name: Install Protoc Plugin for Go
      run: go get -u github.com/golang/protobuf/protoc-gen-go
    
    - name: Generate Sources
      run: |
        LANGS_ARR=($LANGS)
        for LANG in "${LANGS_ARR[@]}"
        do 
            echo "Generating: "$LANG
            mkdir -p ${LANG}
            protoc --${LANG}_out=${LANG} ${PROTO_FILE}
        done

    
      
    - name: Commit files
      run: |
        git add ${LANGS}
        git status ${LANGS}
        if [ -n "$(git status --porcelain $LANGS)" ]; # something is changed
        then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Added generated sources [automated]"
        fi
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.REPO_TOKEN }}
