name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Protoc
      uses: Arduino/actions/setup-protoc@master
    - name: Build C++
      run: protoc --cpp_out=. senml.proto
    - name: Run a multi-line script
      run: ls
