name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Protoc
      uses: Arduino/actions/setup-protoc@master
    - name: Generate C++ Source
      run: mkdir -p cpp && protoc --cpp_out=cpp senml.proto
    - name: Generate Python Source
      run: mkdir -p python && protoc --python_out=python senml.proto
    - name: Generate JavaScript Source
      run: mkdir -p js && protoc --js_out=js senml.proto
    # Golang
    - name: Install Go
      uses: actions/setup-go@v1
    - name: Install protoc Go Plugin
      run: go get -u github.com/golang/protobuf/protoc-gen-go
    - name: Generate Go Source
      run: mkdir -p go && protoc --go_out=go senml.proto
    
      
#     - name: Commit files
#       run: |
#         git config --local user.email "action@github.com"
#         git config --local user.name "GitHub Action"
#         git add cpp python js
#         git commit -m "Updated generated sources"
#     - name: Push changes
#       uses: ad-m/github-push-action@master
#       with:
#         github_token: ${{ secrets.REPO_TOKEN }}
